# Custom Homebrew download strategy for assets in private GitHub release.
#
# Required because:
#   - The github.com/.../releases/download/... URL returns 404 on private
#     repos even with valid OAuth auth.
#   - Only api.github.com/.../releases/assets/{id} works, but asset IDs
#     aren't known until upload time.
#
# This strategy:
#   1. Resolves the asset ID at install time via the GitHub API
#   2. Rewrites the URL to the api.github.com asset URL
#   3. Adds the Authorization header to the download request
#
# Token resolution order:
#   1. HOMEBREW_GITHUB_API_TOKEN env var
#   2. `gh auth token` shell-out (so org members who've run `gh auth login`
#      can install with no env var)
#
# Used by tokenshift.rb (auto-generated by GoReleaser).

require "download_strategy"

class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  def initialize(url, name, version, **meta)
    super
    parse_url_pattern
    set_github_token
    @url = api_asset_url
    @meta[:headers] = (@meta[:headers] || []) + [
      "Accept: application/octet-stream",
      "Authorization: bearer #{@github_token}",
    ]
  end

  private

  def parse_url_pattern
    pattern = %r{https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(.+)}
    match = @url.match(pattern)
    raise CurlDownloadStrategyError, "Invalid GitHub release URL: #{@url}" unless match

    @owner, @repo, @tag, @asset_name = match.captures
  end

  def set_github_token
    @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
    @github_token ||= `gh auth token 2>/dev/null`.chomp
    if @github_token.nil? || @github_token.empty?
      raise CurlDownloadStrategyError,
            "No GitHub token. Set HOMEBREW_GITHUB_API_TOKEN or run `gh auth login`."
    end
  end

  def api_asset_url
    require "json"
    require "net/http"
    require "uri"

    resp = Net::HTTP.get(
      URI.parse("https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}"),
      "Accept"               => "application/vnd.github+json",
      "Authorization"        => "Bearer #{@github_token}",
      "X-GitHub-Api-Version" => "2022-11-28",
    )
    release = JSON.parse(resp)
    asset = release.fetch("assets", []).find { |a| a["name"] == @asset_name }
    if asset.nil?
      raise CurlDownloadStrategyError,
            "Asset '#{@asset_name}' not found in #{@owner}/#{@repo}@#{@tag}"
    end
    asset["url"]
  end
end
