# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private_release_strategy"
class Tokenshift < Formula
  desc "Config-driven CLI proxy that compresses command output to save LLM tokens"
  homepage "https://github.com/pointfiveinc/tokenshift"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pointfiveinc/tokenshift/releases/download/v0.2.3/tokenshift_0.2.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6afa611fc56deea108088f4da2bd7449db4fcb00c4e3455b0b0ae1e60fc939de"

      def install
        bin.install "tokenshift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pointfiveinc/tokenshift/releases/download/v0.2.3/tokenshift_0.2.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5c31824c613462d969eb4d71bf7bd14d0485bf1ec3f6827337d01c0a0e50bafa"

      def install
        bin.install "tokenshift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pointfiveinc/tokenshift/releases/download/v0.2.3/tokenshift_0.2.3_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "e5894e0752de6656ad3589e78effb6c8444cf248cc59b0f89c8ba67d2bc727ed"

        def install
          bin.install "tokenshift"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pointfiveinc/tokenshift/releases/download/v0.2.3/tokenshift_0.2.3_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "e21eaeb090e579d0a5574e2d9c8ef1374b0cabee9e3a41c7a527f52ecf05fc4b"

        def install
          bin.install "tokenshift"
        end
      end
    end
  end

  test do
    system "#{bin}/tokenshift", "version"
  end
end
